package com.example.demo2.common;

public interface ResultCode {
    String SYSTEM_SUCCESS="00000";
    /*String SYSTEM_ERROR_GET_TOKENID ="10001";
    String SYSTEM_ERROR_GET_TOKENID_NAME_NULL ="10001";
    String SYSTEM_ERROR_GET_TOKENID_NAME_SIZE ="10002";
    String SYSTEM_ERROR_GET_TOKENID_PASS_NULL ="10001";*/
    
    //background后台账号
    String BACKGROUND_LOGIN_SUCCESS ="00001";
    String BACKGROUND_LOGIN_FAIL ="10001";
    
    String BACKGROUND_LOGON_SUCCESS ="00002";
    String BACKGROUND_LOGON_ACCOUNT_ERROR ="10002";
    
    String BACKGROUND_LOGON_PWD_ERROR ="10003";
    
    String BACKGROUND_DELETE_SUCCESS ="00004";
    String BACKGROUND_DELETE_FAIL ="10004";
    
    String SYSTEM_SUCCESS_TOKEN ="00005";
    String SYSTEM_ERROR_TOKEN ="10005";
}
